language: php
os: linux

php:
    #- 7.0
    #- 7.1
    - 7.2
    - 7.3
    #- nightly

env:
    global:
        - COVERAGE=0
        - COMPOSER_MEMORY_LIMIT=-1

jobs:
    fast_finish: true
    #allow_failures:
    #- php: nightly

    include:
        - php: 7.2
          env: COVERAGE=1

install:
    # disable xdebug for performance reasons when code coverage is not needed
    - if [[ $COVERAGE = 0 ]]; then phpenv config-rm xdebug.ini || echo "xdebug is not installed"; fi
    - composer install -vvv

script:
    - composer dumpautoload
    - composer pre-commit
    - if [[ $COVERAGE = 1 ]]; then composer test-coverage; fi
    - if [[ $COVERAGE = 1 ]]; then composer test-clover; fi

after_success:
    - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
